export {default as Home} from './Home'
export {default as NotFound} from './NotFound'
export {default as Artists} from './Artists'
export {default as Artist} from './Artists/Artist'
export {default as Albums} from './Albums'
export {default as Album} from './Albums/Album'